#    后续进行加密处理 TODO
spring:
    datasource:
        url: ${touear.mysql.url}
        username: ${touear.mysql.username}
        password: ${touear.mysql.password}

#    redis:
#      password: ${spring.redis.password}


#    application:
#      name: touear-manage